# Generated by Django 5.0.3 on 2024-05-01 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="authors",
            field=models.ManyToManyField(
                related_name="readers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
